### ISSUE TITLE
Thought about applying dirty-matrix in nametable

### ISSUE THREAD

**Issue by GorgonMeducer** [semiversus/jeg#12]
Could we apply dirty-matrix technique by monitoring nametable, if there is no any x/y scrolling ?
So we can only draw the changed tiles.

I also think maybe we can maintain two nametable images, and using memory copy methods to cope with scrolling. 

What do you think?

**Comment by GorgonMeducer** [comment]
Just for your information, currently, ppu_update uses 450ms in average for each frame. (CPU freq 25MHz)

**Comment by semiversus** [comment]
But only if the screen is not scrolling - or I'm wrong?

**Comment by GorgonMeducer** [comment]
Think about the fundamental scheme of scrolling, it's about picking pixels from two logically adjacent images. 
We generate/buffer two images for the two name tables.
Then we forget about the two name tables when doing scrolling, we just pick up pixels from the two images we buffered.

**Comment by semiversus** [comment]
Yeah, thats right, but I thought dirty matrix is used because there is a bottle neck to the actual display controller. Is the display controller able to have a "bigger" image than displayed in his memory? This would be needed to have this scheme be working. Also when scrolling like this inside two nametables there will be a wrap around on the end of the second nametable. It's hard to explain this via text, hope we get a mutual understanding of the problem.

For non scrolling games it will work really well.

**Comment by GorgonMeducer** [comment]
The dirty-matrix can eliminated unnecessary work of PPU, so it saves time used by ppu_update. I don't know what do you mean by saying "have a "bigger" image than displayed in his memory"? We only pick up pixels from the buffered images to generate a normal 256 * 240 frame which will be send to LCD or other display device. In fact, only the ppu_update logic will be changed, the API interfaces will keep the same. 

About the wrapper, it's an implementation problem and I don't think it is a big issue.

**Comment by GorgonMeducer** [comment]
I studied your code and the PPU spec later night, I think I will start to try my idea. How about that I add a dedicated macro option for my alternative of ppu_update in next pull, so we can do the improving simultaneously. Talking with code would be better than pure text some times (not all the time).

^_^

**Comment by semiversus** [comment]
Good idea! Go along

**Comment by GorgonMeducer** [comment]
* Add background buffer for name tables.
   
    * Add Dirty Matrix to background buffer refreshing scheme. Only changed tile will be updated. 
    
    * Add debug mode to show background buffer. 
    
    * Gain > 10% performance improvement.

----------------

I am preparing add dirty matrix for both sprites and background final mixing.

**Comment by GorgonMeducer** [comment]
Since we have dedicated buffers for background, I decide to add a dedicated buffer to sprites. This will reduce the unnecessary rendering of unchanged sprites.

**Comment by GorgonMeducer** [comment]
I have almost finished what I can do for adding dirty-matrix into ppu. It ends up with:
- dedicated screen buffers for name tables
- dedicated buffers for individual sprites

All those buffers are maintained with dirty-matrix technique.
