### ISSUE TITLE
I need permission to add new branch

### ISSUE THREAD

**Issue by GorgonMeducer** [semiversus/jeg#2]
Hi 

I have done some improvements to jeg, but I need permission to create a new branch.
Please help.

Cheers,
Gabriel

**Comment by semiversus** [comment]
Hi,
usually you fork the project and work on (your) fork. To upstream the changes initiate a pull request (see https://help.github.com/articles/creating-a-pull-request-from-a-fork/). Pleased to see your changes!

**Comment by GorgonMeducer** [comment]
thx
