### ISSUE TITLE
macro leftovers?

### ISSUE THREAD

**Issue by semiversus** [semiversus/jeg#21]
I found some `do{ ... }while(false)` constructs in code. Are these left overs from former macro definitions or may I'm missing something?
* https://github.com/semiversus/jeg/blob/ce4c94ace61c9a56470014610e472d5af44958ef/cpu6502.c#L66
* https://github.com/semiversus/jeg/blob/ce4c94ace61c9a56470014610e472d5af44958ef/nes.c#L277
* https://github.com/semiversus/jeg/blob/ce4c94ace61c9a56470014610e472d5af44958ef/ppu.c#L41
* https://github.com/semiversus/jeg/blob/ce4c94ace61c9a56470014610e472d5af44958ef/ppu.c#L359

**Comment by GorgonMeducer** [comment]
“do {
} while(false)”
and 
“do {} while(0)” 
 are very useful structures which have following benefits:

1. they wrap multiple statement as one
2. you can add “if (condition) break;” to do validation, e.g.

do {
    if (<validation a>) {
        break;
    }
    if (<validation b>) {
        break;
    }
    ...
    //! it’s safe to do what we want to do
    ...
} while(false); 

3. It’s possible to limit the range (life-time) of a variable
4. they make a code segment obviouse and limit the range of the code segment
5. they can be easily extracted as functions / macros

**Comment by semiversus** [comment]
seems legit while development but I think it's cleaner without this construction. Is it OK for you to remove in a future point of time when things getting stable?

**Comment by GorgonMeducer** [comment]
I reviewed the code segments you pointed out, all of these do {} while() structure have functionalities, so they cannot be removed. E.g.

The first four you mentioned are used for validation purpose.
The final one is used for limit the life cycle of a local variable chIndex.

If you agree, I will remove those do {} while() structures which have no obviouse functionalities.

**Comment by semiversus** [comment]
OK
