### ISSUE TITLE
Add method to sync update-frame with ppu_update

### ISSUE THREAD

**Issue by GorgonMeducer** [semiversus/jeg#5]
Currently, the example code calls update_frame on each round:

        nes_set_controller(&this.tNESConsole, this.chController[0], this.chController[0]);
        nes_iterate_frame(&this.tNESConsole);
        update_frame(&this.tFrame);

Actually, we concern that this could lead to some unnecessary frame updates before a complete frame is actually ready. Could we add a method to sync up between ppu_update and update_frame?

My proposal is either adding a call-back or a dedicated flag which can be checked by update_frame.

**Comment by semiversus** [comment]
`nes_iterate_frame` is running the 6502 as many cycles as needed to complete a frame. So when `nes_iterate_frame` is returning a full frame is rendered. With `update_frame` this frame is brought to screen.

Running `nes_iterate_frame` should always result (on average) in the same amount of 6502 cycles to be run (as long no other `cpu6502_run` call is done).

Maybe I'm missing the point but there should no further sync be necessary? Indeed a flag to see if the frame is finished (or callback) when using `cpu6502_run` instead `nes_iterate_frame` could be helpful.

**Comment by GorgonMeducer** [comment]
Yes, you are right. I have confirm this by a deep diving into the ppu_update.
You can close this issue now.
