### ISSUE TITLE
Unnecessary pointer validation

### ISSUE THREAD

**Issue by GorgonMeducer** [semiversus/jeg#6]
I have seen an unnecessary pointer validation in the ppu_update code:

          if (ppu->video_frame_data) {
            ppu->video_frame_data[ppu->scanline*256+ppu->cycle-1]=ppu->palette[color];
          }

This kind of validation should be done in the initialisation phase rather than in such a HOTSPOT area. Especially the ppu->video_frame_data is less likely to be changed dynamically (on-fly).

Please consider to remove it.

**Comment by semiversus** [comment]
Actually the intention was to be able to run without graphical output at all. Game logic would require a functional PPU but output could be dropped. Will remove this pointer validation, as there could be much simpler PPU implementation dropping more things. I've used that for a evolutionary algorithmn training to play NES games.

**Comment by GorgonMeducer** [comment]
If you check my pull request, you will find that I have replace it with a callback interface which fulfils your requirements such as running without graphical output and/or cooperating with evolutionary algorithm.
