### ISSUE TITLE
Using callback to replace direct frame-buffer accessing

### ISSUE THREAD

**Issue by GorgonMeducer** [semiversus/jeg#7]
In order to support dirty-matrix technique, I suggest to use callback to replace the direct frame-buffering access:

Original:
ppu->video_frame_data[ppu->scanline*256+ppu->cycle-1]=ppu->palette[color];

Callback:

typedef void ppu_draw_pixel_t (uint_fast8_t y, uint_fast8_t x, uint_fast8_t color);

ppu->draw_pixel(ppu->scanline, ppu->cycle-1, ppu->palette[color]);

I understand that using callback will reduce the memory access performance due to the unnecessary parameter passing, but comparing the performance gain of eliminating refreshing unchanged tiles, it is worth it. 

For PC or other architecture which have rich computing power, the overhead of this callback negligible , but it is vital to enable the dirty-matrix technique which saves a lot of computing power on embedded processors.

**Comment by GorgonMeducer** [comment]
I have sent a pull request about this change and implemented a dirty-matrix on my project.

https://github.com/GorgonMeducer/EmbeddedNES/blob/master/mps2_template/example/LiteNES/src/hal.c

I hope this could be a good prove-of-concept. By using the dirty-matrix, the general game experience has been improved on Cortex-M7 @ 25MHz. 

I will find some STM32 development board which can run higher frequency ( > 100MHz) to demonstrate this project.

I am looking forward to seeing your improvements on PPU.

**Comment by GorgonMeducer** [comment]
Add a dedicated option in jeg_cfg.h

**Comment by semiversus** [comment]
Can this issue be closed? Should be done with your former pull request
